mongodb:
  image: "mongo:3"

redis:
  image: "redis:3"

postgres:
  image: "postgres:9"

memcached:
  image: "memcached"

jenkins:
  build: .
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true -Djava.util.logging.config.file=/var/jenkins_home/log.properties"
  ports:
    - "50000:50000"
    - "8080:8080"
  volumes:
    - /home/jenkins:/var/jenkins_home
  restart: always
  user: jenkins
  links:
    - mongodb
    - redis
    - postgres
    - memcached
